# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfootgeometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dfootgeometry.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x64\x66ootgeometry.proto\"D\n\x13ProcessImageRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x0e\n\x06images\x18\x03 \x03(\x0c\"(\n\x14ProcessImageResponse\x12\x10\n\x08response\x18\x01 \x01(\x05\x32N\n\rDfootgeometry\x12=\n\x0cProcessImage\x12\x14.ProcessImageRequest\x1a\x15.ProcessImageResponse\"\x00\x62\x06proto3')
)




_PROCESSIMAGEREQUEST = _descriptor.Descriptor(
  name='ProcessImageRequest',
  full_name='ProcessImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ProcessImageRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identity', full_name='ProcessImageRequest.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='images', full_name='ProcessImageRequest.images', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=91,
)


_PROCESSIMAGERESPONSE = _descriptor.Descriptor(
  name='ProcessImageResponse',
  full_name='ProcessImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ProcessImageResponse.response', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['ProcessImageRequest'] = _PROCESSIMAGEREQUEST
DESCRIPTOR.message_types_by_name['ProcessImageResponse'] = _PROCESSIMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessImageRequest = _reflection.GeneratedProtocolMessageType('ProcessImageRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSIMAGEREQUEST,
  __module__ = 'dfootgeometry_pb2'
  # @@protoc_insertion_point(class_scope:ProcessImageRequest)
  ))
_sym_db.RegisterMessage(ProcessImageRequest)

ProcessImageResponse = _reflection.GeneratedProtocolMessageType('ProcessImageResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSIMAGERESPONSE,
  __module__ = 'dfootgeometry_pb2'
  # @@protoc_insertion_point(class_scope:ProcessImageResponse)
  ))
_sym_db.RegisterMessage(ProcessImageResponse)



_DFOOTGEOMETRY = _descriptor.ServiceDescriptor(
  name='Dfootgeometry',
  full_name='Dfootgeometry',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessImage',
    full_name='Dfootgeometry.ProcessImage',
    index=0,
    containing_service=None,
    input_type=_PROCESSIMAGEREQUEST,
    output_type=_PROCESSIMAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DFOOTGEOMETRY)

DESCRIPTOR.services_by_name['Dfootgeometry'] = _DFOOTGEOMETRY

# @@protoc_insertion_point(module_scope)
