# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dfootgeometry_pb2 as dfootgeometry__pb2


class DfootgeometryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessImage = channel.unary_unary(
        '/Dfootgeometry/ProcessImage',
        request_serializer=dfootgeometry__pb2.ProcessImageRequest.SerializeToString,
        response_deserializer=dfootgeometry__pb2.ProcessImageResponse.FromString,
        )


class DfootgeometryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ProcessImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DfootgeometryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessImage': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessImage,
          request_deserializer=dfootgeometry__pb2.ProcessImageRequest.FromString,
          response_serializer=dfootgeometry__pb2.ProcessImageResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Dfootgeometry', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
